package com.auco.tempered.config;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import com.electronwill.nightconfig.core.Config;
import com.electronwill.nightconfig.core.UnmodifiableConfig;
import com.electronwill.nightconfig.toml.TomlWriter;
import net.neoforged.neoforge.common.ModConfigSpec;

/** Generates the reference from the spec, so keys, defaults and explanations have one source. */
public final class ConfigExample {
    public static final Path PATH = Path.of(System.getProperty("tempered.projectDir", "."), "config.toml.example");

    public static String render() {
        StringBuilder output = new StringBuilder("""
                # Tempered gameplay configuration reference.
                # Copy to <instance-or-server>/config/tempered/config.toml, then restart the world/server.
                # SERVER settings are authoritative; connected clients receive the active values.
                # An existing world/serverconfig/tempered/config.toml overrides the normal file.
                # Edits while running are pending until restart, including for players joining later.
                # Individual invalid values are corrected to defaults by NeoForge (with a backup).
                # Mismatched Executioner tier-list lengths use the entire default Executioner section.
                # Saved levels/progress survive disabling or lowering caps; effective bonuses use the new cap.
                # Reinforced equipment recalculates when carried/used, retaining its remaining durability fraction.
                # Executioner continues recording progress beyond the current highest tier (integer saturation).
                # Aspects always apply successfully; no application chance or random smithing preview is used.
                # Eligibility remains controlled by datapacks; Aspect acquisition uses the sections below.
                # Aspects have no crafting acquisition recipes; found Aspects are applied through smithing.
                # Inconsistent acquisition count ranges use the default counts (1, 1), preserving other settings.
                # Example: a bonus list [5.0, 17.5] gives two levels with total bonuses of 5% and 17.5%.
                # Example: use milestones [64, 192, 384] for slower Executioner progression.
                # Example: execute chances [0.1, 0.3, 0.75] give 10%, 30%, 75% success at the three tiers.
                # Generated by ./gradlew updateConfigExample. ./gradlew test rejects a stale example.
                """);
        appendSection(output, TemperedConfig.SPEC.getSpec(), List.of());
        return output.toString();
    }

    private static void appendSection(StringBuilder output, UnmodifiableConfig section, List<String> path) {
        var entries = section.entrySet().stream().sorted(Comparator.comparing(UnmodifiableConfig.Entry::getKey)).toList();
        boolean hasValues = entries.stream().anyMatch(entry -> entry.getValue() instanceof ModConfigSpec.ValueSpec);
        if (hasValues) {
            output.append('\n').append('[').append(String.join(".", path)).append("]\n");
            for (var entry : entries) {
                if (entry.getValue() instanceof ModConfigSpec.ValueSpec value) {
                    for (String line : value.getComment().split("\\R")) output.append("# ").append(line).append('\n');
                    // Let the TOML serializer quote strings and encode any future supported value types.
                    Config setting = Config.inMemory();
                    setting.set(entry.getKey(), value.getDefault());
                    output.append(new TomlWriter().writeToString(setting));
                }
            }
        }
        for (var entry : entries) {
            if (entry.getValue() instanceof UnmodifiableConfig nested) {
                List<String> nestedPath = new ArrayList<>(path);
                nestedPath.add(entry.getKey());
                appendSection(output, nested, nestedPath);
            }
        }
    }

    public static void main(String[] args) throws IOException {
        Files.writeString(PATH, render());
    }

    private ConfigExample() {}
}
