@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.auco.tempered.aspect;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;