modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Auco"
description='''
Find Aspects as loot to choose equipment upgrades, earn Affixes through use,
and keep progression through supported upgrades and repairs.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="guideme"
    type="required"
    reason="Provides Tempered's in-game guide."
    versionRange="[${guideme_version},21.2)"
    ordering="AFTER"
    side="BOTH"
